apiVersion: batch/v1
kind: Job
metadata:
  name: math-add-job
spec:
  # Specifies how many pods to create for this job
  completions: 3
  # Specifies how many pods should run in parallel
  parallelism: 3
  template:
    spec:
      containers:
        - name: math-add
          image: ubuntu
          command: ["expr", "3", "+", "2"]
      restartPolicy: OnFailure
